### ISSUE TITLE
Charge Indication not working

### ISSUE THREAD

**Issue by Momolem** [ChrisLauinger77/gnome-shell-extension-HeadsetControl#14]
Hi,

I am facing the problem, that the charging level is not showing :/

My system: Fedora Workstation 38 (Gnome 44)

headsetcontroll is installed:
![image](https://user-images.githubusercontent.com/23556018/236699595-90ff864a-aed0-49a3-a230-fdba5cdbcac1.png)

The command is working fine:
![image](https://user-images.githubusercontent.com/23556018/236699617-c569539c-282b-48ae-be74-c6d1be7c56d0.png)

And I have set the correct command in the extension settings:
![image](https://user-images.githubusercontent.com/23556018/236699692-715e9e12-1d23-4515-aec7-31dbee1b9660.png)

And I added the udev rules as far as I know

Does anyone have an idea why it is not working?

**Comment by ChrisLauinger77** [comment]
can you post a screenshot of the quicksettings control ?

one way to find out whats going on is to enable logging in settings and check the output of

journalctl -f -o cat

Afterwards

**Comment by Momolem** [comment]
Wow you answered quick :) Thank you!

the command you mentioned outputs this:
![image](https://user-images.githubusercontent.com/23556018/236842467-a57c605a-52fe-4960-bc6e-8f46196ff58e.png)

but I still cannot see the percentage of my headset

**Comment by ChrisLauinger77** [comment]
I checked the GIT repo of headsetcontrol binary - he changed the capabilities texts in Nov 2021 over this commit:
https://github.com/Sapd/HeadsetControl/commit/f1b4562de3b4882d74ac8b797f2ba2a148d8751b
It looks like you use a VERY OLD version of headsetcontrol and need to update !

**Comment by Momolem** [comment]
That could be it :/ I installed it via the package manager... maybe i should build the newest version by myself
thanks for your help

**Comment by ChrisLauinger77** [comment]
Intresting - I did not know that fedora provides a package.
He has instructions how to compile it for fedora though. Maybe you wanna ask the fedora guys to update the package.
I update my documentation.

**Comment by Momolem** [comment]
It looks like version 2.6.1 is scheduled for the next fedora version! Thanks again! Currently it is Version 2.4-5

**Comment by ChrisLauinger77** [comment]
Welcome - hope it works now for you as well ..

**Comment by ChrisLauinger77** [comment]
Just found this https://koji.fedoraproject.org/koji/buildinfo?buildID=2165947
