### ISSUE TITLE
Weird behaviour of menu button

### ISSUE THREAD

**Issue by NintyS** [ChrisLauinger77/gnome-shell-extension-HeadsetControl#15]
I saw something like this:
![image](https://github.com/ChrisLauinger77/gnome-shell-extension-HeadsetControl/assets/31569763/10e71b7c-4d44-4298-8d82-9a883351e1a9)
And when I click on that button then it moves:
![image](https://github.com/ChrisLauinger77/gnome-shell-extension-HeadsetControl/assets/31569763/c0d4abee-cb17-48b0-8991-76b64e4888c8)

It's repairing itself when I close menu and open it again, but this is kinda annoying.

**Comment by NintyS** [comment]
PS. This behave this way when [QSTweak] Quick Setting Tweaker is on

**Comment by ChrisLauinger77** [comment]
Not sure what causes this. I try to investigate. Could also be a bug in gnome-shell or QSTweak.

**Comment by NintyS** [comment]
Maybe the button is redrawed? Or you add element as last(?) And not in the special place. ( IDK I did a extension for tests only one ). I will try check why this happends.

**Comment by ChrisLauinger77** [comment]
The only use of the toggle is to show / hide systemindicator icon. (Did not know what else I could use it for and it felt weird to click it and nothing happens).
On toggle the indicator is destroyed and this causes the behaviour.
AFAIK gnome-shell orders the extenions as they are loaded / enabled after the build-in stuff. 
On reopen gnome-shell seems to resort in the order the extensions are loaded.
I doubt this can be changed inside the extension but I am not sure

**Comment by ChrisLauinger77** [comment]
I think it is not worth spending time on this. How often you toggle the systemindicator ?
