### ISSUE TITLE
Include supported brands in the description

### ISSUE THREAD

**Issue by mutlucan96** [ChrisLauinger77/gnome-shell-extension-HeadsetControl#17]
It took me some searching on the web but I'm glad I found this awesome extension. The first thing I did, if there was an extension for my headset, was a search for "steelseries" on Gnome Extensions. I got no results. If you include supported device brands in the description, more people can find this easier IMO.

**Comment by mutlucan96** [comment]
I know how it works. It is required for people to know Spad/HeadsetControl exists in the first place. I didn't know adding keywords would hurt anybody. Something like:
"Gnome Shell Extension to visualize headset status from HeadsetControl (https://github.com/Sapd/HeadsetControl) command line tool which supports some headsets from Corsair, HyperX, Logitech, SteelSeries and ROCCAT."

**Comment by ChrisLauinger77** [comment]
There will always be a brand missing when the commandline tools changes.
